volumes:
  db-data:

services:
  mysql:
    image: mysql:8.4
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWD:-prestashop}
      MYSQL_DATABASE: ${DB_NAME:-prestashop}
    command: --require_secure_transport=OFF
    restart: unless-stopped
    networks:
      - prestashop-network

  prestashop-git:
    hostname: ${PS_HOSTNAME:-localhost}
    build:
      dockerfile: .docker/Dockerfile
      context: .
      args:
        - VERSION=${VERSION:-8.1-apache}
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
        - NODE_VERSION=${NODE_VERSION:-20.17.0}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG:-false}
    environment:
      DISABLE_MAKE: ${DISABLE_MAKE:-0}
      PS_INSTALL_AUTO: ${PS_INSTALL_AUTO:-1}
      DB_PASSWD: ${DB_PASSWD:-prestashop}
      DB_NAME: ${DB_NAME:-prestashop}
      DB_SERVER: ${DB_SERVER:-mysql}
      DB_PREFIX: ${DB_PREFIX:-ps_}
      PS_DOMAIN: ${PS_DOMAIN:-localhost:8001}
      PS_FOLDER_INSTALL: ${PS_FOLDER_INSTALL:-install-dev}
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN:-admin-dev}
      PS_COUNTRY: ${PS_COUNTRY:-fr}
      PS_LANGUAGE: ${PS_LANGUAGE:-en}
      PS_DEV_MODE: ${PS_DEV_MODE:-1}
      PS_ENABLE_SSL: ${PS_ENABLE_SSL:-0}
      PS_ERASE_DB: ${PS_ERASE_DB:-0}
      PS_USE_DOCKER_MAILDEV: ${PS_USE_DOCKER_MAILDEV:-1}
      ADMIN_MAIL: ${ADMIN_MAIL:-demo@prestashop.com}
      ADMIN_PASSWD: ${ADMIN_PASSWD:-Correct Horse Battery Staple}
      BLACKFIRE_ENABLE: ${BLACKFIRE_ENABLE:-0}
      BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID:-0}
      BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN:-0}
    command: /tmp/wait-for-it.sh --timeout=60 --strict mysql:3306 -- /tmp/docker_run_git.sh
    ports:
      - "8001:80"
      - "8002:443"
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html
      # If you develop on Mac or Windows you can remove the vendor/ directory
      # from the bind-mount for better performance by enabling the next line:
      # - /var/www/html/vendor  
      # - /var/www/html/var
      # - /var/www/html/admin-dev/themes/default/node_modules
      # - /var/www/html/admin-dev/themes/new-theme/node_modules
      # - /var/www/html/themes/node_modules
      # - /var/www/html/themes/classic/_dev/node_modules
      # - /var/www/html/themes/hummingbird/node_modules
    networks:
      - prestashop-network

  maildev:
    image: 'maildev/maildev'
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - prestashop-network

networks:
  prestashop-network:
    name: prestashop-network
